### PR TITLE
Directory structure updates

### PR DESCRIPTION
**Pull request by bvennam**

### CODE REVIEW

**Comment by bvennam** [comment]
@csantanapr please review & feel free to merge if it LGTY

**Review by csantanapr — DISMISSED** [review]
Travis tests are not running on PRs

Please enable testing on PRs

**Comment by bvennam** [comment]
we won't merge this one until the fix for deploy package is in.

**Comment by bvennam** [comment]
@dubeejw please merge in if it LGTY.

**Review by dubee — APPROVED** [review]

**Pull request merged**
